version: '3'

services:

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - "all_sauce-static:/usr/src/app/static"
    ports:
      - "8001:8001"
      - "8002:8002"

  all_sauce-static:
    build: ./all_sauce
    volumes:
      - "all_sauce-static:/usr/src/app/static"
    command: python /usr/src/app/manage.py collectstatic --noinput

  all_sauce:
    restart: always
    build: ./all_sauce
    volumes:
      # Production
      #- dabao-cms:/usr/src/app
      # Development
      - ./all_sauce:/usr/src/app
    ports:
      - "8000"
    command: ["/usr/src/app/wait-for-it.sh" , "node1:3306" , "--strict" , "--timeout=300" , "--" , "bash" , "/usr/src/app/script.sh"]

  all_sauce_2:
    restart: always
    build: ./all_sauce
    volumes:
      # Production
      #- dabao-cms:/usr/src/app
      # Development
      - ./all_sauce_2:/usr/src/app
    ports:
      - "8000"
    command: ["/usr/src/app/wait-for-it.sh" , "node2:3306" , "--strict" , "--timeout=300" , "--" , "bash" , "/usr/src/app/script.sh"]
  
  node1:
    image: hauptmedia/mariadb:10.1
    hostname: node1
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - REPLICATION_PASSWORD=test
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node1
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://
    command: --wsrep-new-cluster

  node2:
    image: hauptmedia/mariadb:10.1
    hostname: node2
    links:
      - node1
    ports:
      - 23306:3306
    environment:
      - REPLICATION_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node2
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://node1

  node3:
    image: hauptmedia/mariadb:10.1
    hostname: node3
    links:
      - node1
    ports:
      - 33306:3306
    environment:
      - REPLICATION_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node3
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://node1

volumes:
  all_sauce-static: